import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { usePreset } from '@/hooks/usePreset';
import { useMidiDevice } from '@/hooks/useMidiDevice';
import { useLooper } from '@/hooks/useLooper';
import { useDrumMachine } from '@/hooks/useDrumMachine';
import { useAudioEngine } from '@/components/AudioEngineProvider';
import {
  defaultLooperBindings,
  applyExp,
  type LooperBindings,
} from '@/core/looperBindings';
import { loadLooperStore, saveLooperStore } from '@/core/looperTriggers';
import { useLooperTriggers } from '@/hooks/useLooperTriggers';
import { PRSTDecoder } from '@/core/PRSTDecoder';
import { PRSTEncoder } from '@/core/PRSTEncoder';
import { pushPresetToDevice, type PushProgress } from '@/core/devicePush';
import { EFFECT_MAP } from '@/core/effectNames';
import type { GP200Preset } from '@/core/types';

import { Landing } from '@/components/Landing';
import { Guide } from '@/components/Guide';
import { PedalBoard, type PedalBoardProps } from '@/components/board/PedalBoard';
import { useIsPhone } from '@/hooks/useMediaQuery';

// Lazy so the phone tree and its stylesheet stay out of the desktop bundle.
const MobileShell = lazy(() => import('@/components/mobile/MobileShell'));
import { DeviceSlotBrowser } from '@/components/DeviceSlotBrowser';
import { FirmwareCompatDialog } from '@/components/FirmwareCompatDialog';
import { ExportPresetDialog } from '@/components/ExportPresetDialog';
import {
  PatchManagerSheet,
  type BulkExportProgress,
} from '@/components/PatchManagerSheet';
import { createDefaultPreset } from '@/core/defaultPreset';
import { createZip, type ZipEntry } from '@/core/zipStore';
import { SysExCodec } from '@/core/SysExCodec';
import { track, trackVirtualPageView } from '@/core/analytics';
import { useEngagementTracking } from '@/hooks/useEngagementTracking';

/** Trigger a browser download for generated bytes. */
function downloadBlob(bytes: Uint8Array<ArrayBuffer> | ArrayBuffer, filename: string) {
  const blob = new Blob([bytes], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Slot filename like "63-B American Idiot.prst" (path separators stripped). */
function slotFilename(slot: number, name: string | null): string {
  const label = SysExCodec.slotToLabel(slot);
  const safeName = (name ?? 'preset').replace(/[/\\]/g, '_').trim() || 'preset';
  return `${label} ${safeName}.prst`;
}

function App() {
  const {
    preset, loadPreset, setPatchName, setAuthor, toggleEffect, changeEffect,
    reorderEffects, setParam, setFxLoopSend, setFxLoopReturn, setCtrlBlock,
    setCtrlMask, setExpAssignment, setPatchVolume, setPatchPan, setPatchTempo,
    reset,
  } = usePreset();
  const midiDevice = useMidiDevice();
  const isPhone = useIsPhone();
  const audioEngine = useAudioEngine();
  const looper = useLooper(audioEngine);
  // Practice drum machine: lives here (not in a drawer) so the beat keeps
  // playing while the drawer is closed and across the phone/desktop swap.
  const drumMachine = useDrumMachine(audioEngine);

  // Loop-station hardware bindings. State drives the LooperPanel UI; the ref
  // mirror is what the once-per-connection MIDI callbacks read (so they see the
  // current map without re-registering); same pattern as presetRef below.
  const [looperBindings, setLooperBindings] = useState<LooperBindings>(() => {
    return loadLooperStore()?.bindings ?? defaultLooperBindings;
  });
  const looperBindingsRef = useRef(looperBindings);
  looperBindingsRef.current = looperBindings;
  const looperRef = useRef(looper);
  looperRef.current = looper;

  // Whether the looper dialog is open (reported up from PedalBoard).
  // Ref only, nothing renders from it: the MIDI tap reads it to decide if a
  // learned stomp is hijacked into a looper action or left to the pedal.
  const looperPanelOpenRef = useRef(false);
  const looperTriggers = useLooperTriggers({
    midiDevice,
    looperRef,
    panelOpenRef: looperPanelOpenRef,
  });

  // Persist bindings + learned triggers so they survive a reload.
  useEffect(() => {
    saveLooperStore(looperBindings, looperTriggers.triggers);
  }, [looperBindings, looperTriggers.triggers]);

  // NOTE: the Loop Station does NOT rewrite the GP-200's global FootSwitch
  // settings. Two attempts at that "takeover" have now been reverted (c380497,
  // then again 2026-07-18): the settings protocol is write-only, so whatever
  // the app writes on open cannot be read back and restored on close — it
  // clobbers the user's real FS Mode and TAP targets for good. The second
  // attempt broke a user's working Stomp configuration.
  //
  // The pedal is therefore left alone. In Stomp mode a press emits the
  // effect-toggle frame the MIDI-learn tap recognizes, and the hijack path
  // sends a toggle-back to undo it (see useLooperTriggers / revertFor). That
  // undo covers ONE effect block, so it is correct only for a switch that
  // toggles one block — hence the warning in LooperPanel telling the user to
  // clear extra CTRL assignments from a switch before binding it.

  const [dragIndex, setDragIndex] = useState<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const [slotBrowserMode, setSlotBrowserMode] = useState<'pull' | 'push' | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [showExportDialog, setShowExportDialog] = useState(false);
  // Full-page guide overlays both landing and board (no router). Back just
  // clears this, falling through to Landing or PedalBoard per `preset`.
  const [view, setView] = useState<'landing' | 'guide'>('landing');
  const [firmwareWarningDismissed, setFirmwareWarningDismissed] = useState(false);

  // Engagement analytics. No-op unless this is a production build served from a
  // production host (see src/core/analytics.ts), so dev and tests never report.
  const { markEditorEntry, trackPanelOpen } = useEngagementTracking({
    status: midiDevice.status,
    deviceInfo: midiDevice.deviceInfo,
    errorMessage: midiDevice.errorMessage,
    hasPreset: preset !== null,
    isPhone,
    audioActive: audioEngine.active,
    audioError: audioEngine.error,
    looperTrackCount: looper.tracks.length,
    drumsPlaying: drumMachine.playing,
    drumKit: drumMachine.kitId,
    drumPattern: drumMachine.patternId,
    drumBpm: drumMachine.bpm,
  });

  // One guide entry point for both the landing link and the deck button, so the
  // virtual page view can't be attached to one and forgotten on the other.
  const openGuide = useCallback(() => {
    setView('guide');
    trackVirtualPageView('#guide', 'Guide');
    track('view_change', { view: 'guide' });
  }, []);
  // Per-patch VOL/PAN/TEMPO now live in the preset (decoded from the .prst /
  // device dump), so the deck reflects the loaded patch instead of a constant.
  const patchVolume = preset?.patchVolume ?? 50;
  const patchPan = preset?.patchPan ?? 0;
  const patchTempo = preset?.patchTempo ?? 120;

  const [pushProgress, setPushProgress] = useState<PushProgress | null>(null);
  const pushAbortRef = useRef<AbortController | null>(null);

  const [showPatchManager, setShowPatchManager] = useState(false);
  const [bulkProgress, setBulkProgress] = useState<BulkExportProgress | null>(null);
  const bulkCancelRef = useRef(false);

  // Synchronous view of the preset for device-message validation callbacks
  // (the callbacks are registered once per connection, so they'd otherwise
  // close over a stale preset).
  const presetRef = useRef<GP200Preset | null>(preset);
  presetRef.current = preset;

  // Reset the firmware warning once the device disconnects, so reconnecting
  // to a different (or updated) device shows the warning fresh if it applies.
  useEffect(() => {
    if (midiDevice.status === 'disconnected') setFirmwareWarningDismissed(false);
  }, [midiDevice.status]);

  // Ask for audio capture as soon as the board opens, so the permission
  // prompt fires up front and the IN/OUT meters show by default instead of
  // hiding behind the AUDIO IN button. Once only: after a denial or a manual
  // ✕, the AudioMeters button stays as the fallback and we don't re-prompt.
  const audioAutoRequested = useRef(false);
  useEffect(() => {
    if (!preset || audioAutoRequested.current) return;
    audioAutoRequested.current = true;
    void audioEngine.enable();
  }, [preset, audioEngine]);

  // Send the whole preset to the device for live preview (no flash write).
  // Aborts any push still in flight so two loads never interleave on the wire.
  const sendPresetToDevice = useCallback(async (decoded: GP200Preset) => {
    if (midiDevice.status !== 'connected') return;
    pushAbortRef.current?.abort();
    const ac = new AbortController();
    pushAbortRef.current = ac;
    setPushProgress({ completed: 0, total: decoded.effects.length * 2, phase: 'configuring' });
    try {
      await pushPresetToDevice(
        decoded,
        {
          sendEffectChange: midiDevice.sendEffectChange,
          sendParamChange: midiDevice.sendParamChange,
          sendToggle: midiDevice.sendToggle,
          sendReorder: midiDevice.sendReorder,
          sendAuthor: midiDevice.sendAuthor,
          sendPatchVolume: midiDevice.sendPatchVolume,
          sendPatchPan: midiDevice.sendPatchPan,
          sendPatchTempo: midiDevice.sendPatchTempo,
        },
        {
          signal: ac.signal,
          onProgress: (p) => { if (!ac.signal.aborted) setPushProgress(p); },
        },
      );
    } finally {
      if (pushAbortRef.current === ac) pushAbortRef.current = null;
    }
    // midiDevice is a fresh object every render (see useMidiDevice/useMidiSend);
    // depending on midiDevice.status alone avoids re-creating this callback (and
    // therefore re-triggering effects that depend on it) on every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  // Clear the "done" push indicator a moment after it finishes.
  useEffect(() => {
    if (pushProgress?.phase !== 'done') return;
    const id = setTimeout(() => setPushProgress(null), 2000);
    return () => clearTimeout(id);
  }, [pushProgress]);

  // Abort an in-flight push the moment the device drops.
  useEffect(() => {
    if (midiDevice.status !== 'connected') {
      pushAbortRef.current?.abort();
      pushAbortRef.current = null;
      setPushProgress(null);
    }
  }, [midiDevice.status]);

  // After connect: if the local cache seeded a full set of names (progress
  // already 256), silently re-verify them against the device in the background;
  // otherwise fill in the missing names with the visible loading pass.
  useEffect(() => {
    if (midiDevice.status !== 'connected') return;
    if (midiDevice.namesLoadProgress < 256) {
      midiDevice.loadPresetNames();
    } else {
      midiDevice.syncPresetNames();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  // Mirror hardware-initiated changes (knob turns, on-device toggles/effect
  // swaps, slot changes) back into local state; the device is the source of
  // truth for its own editing buffer, which isn't reflected in saved data.
  useEffect(() => {
    if (midiDevice.status !== 'connected') return;
    midiDevice.setOnDeviceToggle((blockIndex, enabled) => toggleEffect(blockIndex, enabled));
    return () => midiDevice.setOnDeviceToggle(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  useEffect(() => {
    if (midiDevice.status !== 'connected') return;
    // Hardware footswitch toggles emit effect-change-shaped frames with the
    // effect id zeroed out (decodes to COMP). Validate before applying: the
    // id must exist, the block's module can't change on hardware, and a
    // same-id "change" is a toggle ack, not a swap; applying it would reset
    // the params to defaults. Return value tells the dispatcher whether to
    // suppress the FX-state messages that follow a real swap.
    midiDevice.setOnDeviceEffectChange((blockIndex, effectId) => {
      const slot = presetRef.current?.effects.find((e) => e.slotIndex === blockIndex);
      const next = EFFECT_MAP[effectId];
      if (!slot || !next) return false;
      if (slot.effectId === effectId) return false;
      const cur = EFFECT_MAP[slot.effectId];
      if (cur && cur.module !== next.module) return false;
      changeEffect(blockIndex, effectId);
      return true;
    });
    return () => midiDevice.setOnDeviceEffectChange(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  // Once connected, mirror the device's active preset into the editor; the
  // handshake already pulled it (midiDevice.currentPreset); the user shouldn't
  // have to press LOAD to see what their pedal is doing.
  useEffect(() => {
    if (midiDevice.status === 'connected' && midiDevice.currentPreset) {
      markEditorEntry('device');
      loadPreset(midiDevice.currentPreset);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  useEffect(() => {
    if (midiDevice.status !== 'connected') return;
    midiDevice.setOnDeviceParamChange((blockIndex, paramIndex, value) => setParam(blockIndex, paramIndex, value));
    return () => midiDevice.setOnDeviceParamChange(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  // Loop-station EXP binding. (Footswitches are NOT wired here: the GP-200
  // doesn't emit the standard CC frames midiControlMap.ts hypothesizes, so
  // stomps reach the looper through the MIDI-learn tap in useLooperTriggers.)
  // The callback reads the ref mirrors so it stays registered once per
  // connection.
  useEffect(() => {
    if (midiDevice.status !== 'connected') return;
    midiDevice.setOnExpPosition((value) => {
      const target = looperBindingsRef.current.expTarget;
      if (!target) return;
      const gain = applyExp(value);
      if (target.kind === 'selectedTrackGain') {
        const selected = looperRef.current.selectedTrack;
        if (selected !== null) looperRef.current.setTrackGain(selected, gain);
        return;
      }
      looperRef.current.setMasterGain(gain);
    });
    return () => midiDevice.setOnExpPosition(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  useEffect(() => {
    if (midiDevice.status !== 'connected') return;
    midiDevice.setOnDeviceChange(async (slot) => {
      if (slot === null) return;
      try {
        const fresh = await midiDevice.pullPreset(slot);
        loadPreset(fresh);
      } catch {
        // Device slot switched but the read failed, so keep showing the last
        // loaded preset rather than clearing the editor.
      }
    });
    return () => midiDevice.setOnDeviceChange(null);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [midiDevice.status]);

  // Stable reference (useCallback([]) inside useMidiDevice), safe to close over.
  const saveToSlot = midiDevice.saveToSlot;
  const handleFile = useCallback((buffer: Uint8Array) => {
    try {
      const decoded = new PRSTDecoder(buffer).decode();
      markEditorEntry('import');
      loadPreset(decoded);
      setLoadError(null);
      track('preset_import', { target: 'editor', ok: true });
      // Live-push the import, then commit it to the active slot (the SAVE
      // flow), so an import lands on the pedal permanently without a
      // separate save step. Both no-op while disconnected; saveToSlot
      // resolves the active slot from its own ref, so no stale closure.
      // Known gap: CTRL footswitch masks don't survive this (no live opcode;
      // the flash-upload alternative is rejected by real hardware).
      void (async () => {
        await sendPresetToDevice(decoded);
        await new Promise((settle) => setTimeout(settle, 250));
        await saveToSlot(decoded.patchName);
      })().catch(() => setLoadError('Failed to save to device'));
    } catch (err) {
      let message = String(err);
      if (err instanceof Error) message = err.message;
      setLoadError(`Error loading file: ${message}`);
      track('preset_import', { target: 'editor', ok: false });
    }
  }, [loadPreset, sendPresetToDevice, saveToSlot, markEditorEntry]);

  function handleExportConfirm(name: string, author: string | undefined, slot: number) {
    if (!preset) return;
    setPatchName(name);
    if (author !== undefined) setAuthor(author);
    const encoded = new PRSTEncoder().encode({ ...preset, patchName: name, author, slotIndex: slot });
    downloadBlob(encoded, `${name || 'preset'}.prst`);
    setShowExportDialog(false);
    track('preset_export', { scope: 'editor' });
  }

  // ── Patch-manager handlers ────────────────────────────────────────────
  async function handleActivateSlot(slot: number) {
    if (midiDevice.status !== 'connected') return;
    // Switch the device, then pull the slot and mirror it into the board.
    // We can't rely on the incoming slot-change echo here: sendSlotChange
    // synchronously advances currentSlotRef (via onSlotChange), so the echo
    // matches the "same-slot frame" branch in useMidiDevice and is ignored,
    // meaning onDeviceChange never fires. Pulling explicitly (like OPEN /
    // handlePullConfirm) keeps the UI in sync regardless of the echo.
    midiDevice.sendSlotChange(slot);
    try {
      const pulled = await midiDevice.pullPreset(slot);
      markEditorEntry('slot');
      loadPreset(pulled);
      setLoadError(null);
    } catch {
      setLoadError('Failed to load preset from device');
    }
  }

  async function handleOpenInEditorSlot(slot: number) {
    try {
      const pulled = await midiDevice.pullPreset(slot);
      markEditorEntry('slot');
      loadPreset(pulled);
      if (midiDevice.status === 'connected') midiDevice.sendSlotChange(slot);
      setLoadError(null);
    } catch {
      setLoadError('Failed to load preset from device');
    }
  }

  async function handleExportSlot(slot: number) {
    try {
      const pulled = await midiDevice.pullPreset(slot);
      const encoded = new PRSTEncoder().encode({ ...pulled, slotIndex: slot });
      downloadBlob(encoded, slotFilename(slot, pulled.patchName));
      setLoadError(null);
      track('preset_export', { scope: 'slot' });
    } catch {
      setLoadError(`Failed to export ${SysExCodec.slotToLabel(slot)} from device`);
    }
  }

  async function handleExportSlots(slots: number[]) {
    if (bulkProgress) return; // one bulk export at a time
    bulkCancelRef.current = false;
    setBulkProgress({ done: 0, total: slots.length });
    const entries: ZipEntry[] = [];
    let failed = 0;
    try {
      for (let i = 0; i < slots.length; i++) {
        if (bulkCancelRef.current) break;
        const slot = slots[i];
        try {
          const pulled = await midiDevice.pullPreset(slot);
          entries.push({
            name: slotFilename(slot, pulled.patchName),
            data: new Uint8Array(new PRSTEncoder().encode({ ...pulled, slotIndex: slot })),
          });
        } catch {
          // Skip unreadable slots (e.g. factory 249–255) but keep going.
          failed++;
        }
        setBulkProgress({ done: i + 1, total: slots.length });
      }
      if (entries.length > 0) {
        downloadBlob(createZip(entries), 'gp200-patches.zip');
        track('preset_export', { scope: 'bulk' });
      }
      if (failed > 0) {
        setLoadError(`Bulk export finished: ${failed} slot(s) could not be read`);
      }
    } finally {
      setBulkProgress(null);
      // pullPreset paused the background name enumeration; resume it.
      if (midiDevice.status === 'connected' && midiDevice.namesLoadProgress < 256) {
        void midiDevice.loadPresetNames();
      }
    }
  }

  async function handleImportToSlot(slot: number, bytes: Uint8Array) {
    try {
      const decoded = new PRSTDecoder(bytes).decode();
      // Flash-upload path (chunked 0x12/0x20, mirrors the official editor):
      // full fidelity including the CTRL/EXP controls tail, and much faster
      // than the per-parameter writePresetToSlot fallback.
      await midiDevice.pushPreset(decoded, slot);
      setLoadError(null);
      track('preset_import', { target: 'slot', ok: true });
    } catch (err) {
      let detail = String(err);
      if (err instanceof Error) detail = err.message;
      setLoadError(`Failed to write to ${SysExCodec.slotToLabel(slot)}: ${detail}`);
      track('preset_import', { target: 'slot', ok: false });
    }
  }

  async function handleRenameSlot(slot: number, name: string) {
    try {
      await midiDevice.renameSlot(slot, name);
      setLoadError(null);
    } catch {
      setLoadError(`Failed to rename ${SysExCodec.slotToLabel(slot)}`);
    }
  }

  function handleOpenPatchManager() {
    setShowPatchManager(true);
    trackPanelOpen('patch_manager');
    if (midiDevice.status === 'connected' && midiDevice.namesLoadProgress < 256) {
      void midiDevice.loadPresetNames();
    }
  }

  async function handlePullConfirm(slot: number) {
    setSlotBrowserMode(null);
    try {
      const pulled = await midiDevice.pullPreset(slot);
      markEditorEntry('slot');
      loadPreset(pulled);
      if (midiDevice.status === 'connected') midiDevice.sendSlotChange(slot);
      setLoadError(null);
    } catch {
      setLoadError('Failed to load preset from device');
    }
  }

  async function handlePushConfirm(slot: number) {
    if (!preset) return;
    try {
      await midiDevice.pushPreset(preset, slot);
      setLoadError(null);
    } catch {
      setLoadError('Failed to save to device');
    } finally {
      setSlotBrowserMode(null);
    }
  }

  async function handleSaveToActiveSlot() {
    if (!preset || midiDevice.currentSlot === null) return;
    // Save-commit persists the device's edit buffer, which every live edit
    // (toggle, param, reorder, VOL/PAN/TEMPO, EXP) already reached. CTRL
    // footswitch masks are the one thing it cannot carry — no live opcode is
    // known — and the flash-upload alternative is rejected by real hardware
    // (docs/protocol-capture.md §0.1), so this stays the save path until the
    // upload finalize is captured.
    await midiDevice.saveToSlot(preset.patchName, midiDevice.currentSlot);
  }

  function handleOpenBrowser(mode: 'pull' | 'push') {
    setSlotBrowserMode(mode);
    trackPanelOpen('slot_browser');
    if (midiDevice.namesLoadProgress < 256) midiDevice.loadPresetNames();
  }

  // Landing "open current preset": the auto-load effect only fires on the
  // connect transition, so after a deck CLOSE the handshake preset is still
  // cached; fall back to a fresh pull if it isn't.
  async function handleOpenCurrent() {
    markEditorEntry('device');
    if (midiDevice.currentPreset) {
      loadPreset(midiDevice.currentPreset);
      return;
    }
    if (midiDevice.currentSlot === null) return;
    try {
      loadPreset(await midiDevice.pullPreset(midiDevice.currentSlot));
      setLoadError(null);
    } catch {
      setLoadError('Failed to load preset from device');
    }
  }

  // Slot mutation handlers shared by the list view and the board view:
  // update local preset state, mirror to the device when connected.
  const handleSlotToggle = useCallback((slotIndex: number, currentlyEnabled: boolean) => {
    toggleEffect(slotIndex);
    if (midiDevice.status === 'connected') midiDevice.sendToggle(slotIndex, !currentlyEnabled);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [toggleEffect, midiDevice.status]);

  const handleSlotEffectChange = useCallback((slotIndex: number, effectId: number) => {
    changeEffect(slotIndex, effectId);
    if (midiDevice.status === 'connected') midiDevice.sendEffectChange(slotIndex, effectId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [changeEffect, midiDevice.status]);

  const handleSlotParamChange = useCallback((slotIndex: number, effectId: number, paramIndex: number, value: number) => {
    setParam(slotIndex, paramIndex, value);
    if (midiDevice.status === 'connected') midiDevice.sendParamChange(slotIndex, paramIndex, effectId, value);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [setParam, midiDevice.status]);

  const handleDragStart = useCallback((index: number) => setDragIndex(index), []);
  const handleDragOver = useCallback((e: React.DragEvent, index: number) => {
    e.preventDefault();
    setDragOverIndex(index);
  }, []);

  // Safety net for the drag state. The React onDragEnd on the board wrapper only
  // fires if the event can bubble from the source pedal, and a cross-row move
  // unmounts that pedal (the rows are separate parents). A window listener has no
  // such dependency, so drag state can never stay stuck — which matters because a
  // stuck dragIndex hides every cable on the board until reload.
  useEffect(() => {
    const clear = () => {
      setDragIndex(null);
      setDragOverIndex(null);
    };
    window.addEventListener('dragend', clear);
    window.addEventListener('drop', clear);
    return () => {
      window.removeEventListener('dragend', clear);
      window.removeEventListener('drop', clear);
    };
  }, []);

  // Shared by drag-and-drop and keyboard reordering. slotIndex (the immutable
  // PRST block identity) is preserved by reorderEffects; only array order changes.
  const moveSlot = useCallback((fromIndex: number, toIndex: number) => {
    if (!preset) return;
    if (fromIndex === toIndex || toIndex < 0 || toIndex >= preset.effects.length) return;
    reorderEffects(fromIndex, toIndex);
    if (midiDevice.status === 'connected') {
      const order = preset.effects.map((e) => e.slotIndex);
      const [moved] = order.splice(fromIndex, 1);
      order.splice(toIndex, 0, moved);
      midiDevice.sendReorder(order, preset.fxLoopSend, preset.fxLoopReturn);
    }
  }, [preset, reorderEffects, midiDevice]);

  const handleDrop = useCallback((toIndex: number) => {
    if (dragIndex !== null) moveSlot(dragIndex, toIndex);
    setDragIndex(null);
    setDragOverIndex(null);
  }, [dragIndex, moveSlot]);

  const firmwareOk = midiDevice.deviceInfo?.versionAccepted ?? false;
  const showFirmwareDialog =
    midiDevice.status === 'connected' &&
    midiDevice.deviceInfo !== null &&
    !firmwareOk &&
    !firmwareWarningDismissed;

  if (view === 'guide') {
    return (
      <Guide
        onBack={() => {
          setView('landing');
          track('view_change', { view: preset ? 'board' : 'landing' });
        }}
      />
    );
  }

  if (!preset) {
    return (
      <Landing
        midiDevice={midiDevice}
        onOpenBlank={() => {
          markEditorEntry('blank');
          loadPreset(createDefaultPreset());
        }}
        onOpenCurrent={() => void handleOpenCurrent()}
        onOpenGuide={openGuide}
        loadError={loadError}
        onDismissError={() => setLoadError(null)}
      />
    );
  }

  // One props object feeds both the desktop board and the phone shell, so a new
  // capability can't reach one tree and silently skip the other: adding a field
  // to PedalBoardProps is a type error here until it's supplied, and both
  // branches receive it. All logic stays here; the trees differ only in layout.
  const boardProps: PedalBoardProps = {
    preset: preset,
    onToggle: handleSlotToggle,
    onChangeEffect: handleSlotEffectChange,
    onParamChange: handleSlotParamChange,
    onMove: moveSlot,
    dragIndex: dragIndex,
    dragOverIndex: dragOverIndex,
    onDragStart: handleDragStart,
    onDragOver: handleDragOver,
    onDrop: handleDrop,
    patchVolume: patchVolume,
    patchPan: patchPan,
    patchTempo: patchTempo,
    currentSlot: midiDevice.currentSlot,
    connected: midiDevice.status === 'connected',
    onLoadRequest: () => handleOpenBrowser('pull'),
    onSaveToActiveSlot: midiDevice.status === 'connected' ? handleSaveToActiveSlot : undefined,
    onPatchNameChange: setPatchName,
    onAuthorChange: setAuthor,
    onVolumeChange: (v) => { setPatchVolume(v); if (midiDevice.status === 'connected') midiDevice.sendPatchVolume(v); },
    onPanChange: (pan) => {
      setPatchPan(pan);
      // sendPatchPan takes the device encoding: left pan = 256 + signed value.
      if (midiDevice.status === 'connected') midiDevice.sendPatchPan(pan & 0xFF);
    },
    onTempoChange: (v) => { setPatchTempo(v); if (midiDevice.status === 'connected') midiDevice.sendPatchTempo(v); },
    onCloseRequest: reset,
    onFxSendChange: (pos) => {
      const clamped = Math.max(1, Math.min(10, pos));
      const nextReturn = Math.max(clamped, preset.fxLoopReturn);
      const sendChanged = clamped !== preset.fxLoopSend;
      const returnPushed = nextReturn !== preset.fxLoopReturn;
      setFxLoopSend(clamped);
      if (midiDevice.status === 'connected') {
        const order = preset.effects.map((e) => e.slotIndex);
        if (sendChanged) midiDevice.sendFxLoopMove(order, clamped, nextReturn, 'send');
        if (returnPushed) midiDevice.sendFxLoopMove(order, clamped, nextReturn, 'return');
      }
    },
    onFxReturnChange: (pos) => {
      const clamped = Math.max(1, Math.min(10, pos));
      const nextSend = Math.min(clamped, preset.fxLoopSend);
      const returnChanged = clamped !== preset.fxLoopReturn;
      const sendPushed = nextSend !== preset.fxLoopSend;
      setFxLoopReturn(clamped);
      if (midiDevice.status === 'connected') {
        const order = preset.effects.map((e) => e.slotIndex);
        if (returnChanged) midiDevice.sendFxLoopMove(order, nextSend, clamped, 'return');
        if (sendPushed) midiDevice.sendFxLoopMove(order, nextSend, clamped, 'send');
      }
    },
    onExpParamSelect: (page, item, blockIndex, paramIdx) => {
      // Persist with the patch; also apply live when a device is attached
      // (there is no live "unassign" message; that lands on SAVE).
      setExpAssignment(page, item, { blockIndex, paramIndex: paramIdx });
      if (midiDevice.status === 'connected' && blockIndex !== null) {
        midiDevice.sendExpParamSelect(page, item, blockIndex, paramIdx);
      }
    },
    onExpMinMax: (page, item, min, max) => {
      setExpAssignment(page, item, { min, max });
      if (midiDevice.status === 'connected') {
        midiDevice.sendExpMinMax(page, item, min, max);
      }
    },
    onCtrlBlockToggle: setCtrlBlock,
    onCtrlClear: (ctrlIndex) => setCtrlMask(ctrlIndex, 0),
    onOpenPatchManager: handleOpenPatchManager,
    onActivateSlot: handleActivateSlot,
    onOpenGuide: openGuide,
    onPanelOpen: trackPanelOpen,
    looper: looper,
    looperBindings: looperBindings,
    onLooperBindingsChange: setLooperBindings,
    onLooperDrawerOpenChange: (open) => {
      looperPanelOpenRef.current = open;
      // Closing the dialog disarms any in-progress MIDI-learn so a stray
      // stomp doesn't bind after the panel is gone.
      if (!open) looperTriggers.cancelLearn();
    },
    looperTriggers: looperTriggers.triggers,
    looperArmedAction: looperTriggers.armedAction,
    onLooperArmLearn: looperTriggers.armLearn,
    onLooperClearTrigger: looperTriggers.clearTrigger,
    onLooperClearAll: looperTriggers.clearAllTriggers,
    looperLearnNotice: looperTriggers.learnNotice,
    drumMachine: drumMachine,
    sendCC: midiDevice.sendCC,
    ccChannel: midiDevice.ccChannel,
    onCcChannelChange: midiDevice.setCcChannel,
    onEnableAudio: () => void audioEngine.enable(),
    audioStarting: audioEngine.starting,
    onConnectRequest: () => void midiDevice.connect(),
    onDisconnect: midiDevice.disconnect,
    onPushRequest: () => handleOpenBrowser('push'),
    pushProgress: pushProgress,
    firmware: midiDevice.deviceInfo?.firmwareValues.join('.') || null,
  };

  return (
    <div className="app-shell w-full flex flex-col overflow-hidden">
      {loadError && (
        <div className="mx-4 mt-3 mb-2 px-4 py-3 rounded-lg font-mono-display text-sm flex items-center justify-between bg-accent-red/10 border border-accent-red/30 text-accent-red">
          <span>{loadError}</span>
          <button onClick={() => setLoadError(null)} className="ml-3 font-bold">✕</button>
        </div>
      )}

      {/* THE view. Below 640px the pedalboard is replaced wholesale by the
          phone shell — the board is built around fixed-width enclosures in a
          horizontal stage and does not fold to a phone. The two trees never
          coexist; all state lives out here and survives the swap. */}
      {isPhone ? (
        <Suspense fallback={<div className="flex-1" />}>
          <MobileShell {...boardProps} />
        </Suspense>
      ) : (
        <div
          className="flex-1 min-h-0 flex flex-col"
          onDragEnd={() => { setDragIndex(null); setDragOverIndex(null); }}
        >
          <PedalBoard {...boardProps} />
        </div>
      )}

      <PatchManagerSheet
        open={showPatchManager}
        onClose={() => setShowPatchManager(false)}
        connected={midiDevice.status === 'connected'}
        presetNames={midiDevice.presetNames}
        namesLoadProgress={midiDevice.namesLoadProgress}
        namesSyncing={midiDevice.namesSyncing}
        currentSlot={midiDevice.currentSlot}
        onActivate={handleActivateSlot}
        onOpenInEditor={handleOpenInEditorSlot}
        onExportSlot={handleExportSlot}
        onExportSlots={handleExportSlots}
        bulkProgress={bulkProgress}
        onCancelBulk={() => { bulkCancelRef.current = true; }}
        onImportToSlot={handleImportToSlot}
        onRenameSlot={handleRenameSlot}
        onRefreshNames={() => void midiDevice.refreshNames()}
        onImportFile={handleFile}
        onExportRequest={() => setShowExportDialog(true)}
      />

      {slotBrowserMode && (
        <DeviceSlotBrowser
          mode={slotBrowserMode}
          presetNames={midiDevice.presetNames}
          namesLoadProgress={midiDevice.namesLoadProgress}
          currentSlot={midiDevice.currentSlot}
          onConfirm={slotBrowserMode === 'pull' ? handlePullConfirm : handlePushConfirm}
          onCancel={() => setSlotBrowserMode(null)}
        />
      )}

      {showFirmwareDialog && midiDevice.deviceInfo && (
        <FirmwareCompatDialog
          detectedVersion={midiDevice.deviceInfo.firmwareValues.join('.') || 'unknown'}
          onContinue={() => setFirmwareWarningDismissed(true)}
          onDisconnect={() => { midiDevice.disconnect(); setFirmwareWarningDismissed(true); }}
        />
      )}

      {/* Mounted only while open so the name/author/slot fields reseed from
          the preset current at open time (they are useState-initialized). */}
      {showExportDialog && (
        <ExportPresetDialog
          open
          onClose={() => setShowExportDialog(false)}
          initialName={preset.patchName}
          initialAuthor={preset.author}
          initialSlot={preset.slotIndex}
          onConfirm={handleExportConfirm}
        />
      )}
    </div>
  );
}

export default App;
