// @vitest-environment node
import { describe, it, expect } from 'vitest';

/**
 * The most important test in the SEO work, and the only one that runs in a
 * bare Node environment on purpose.
 *
 * Every guide page is generated by rendering src/prerender/entry-server.tsx
 * with no DOM at all. That works only because its import closure is free of
 * browser globals — no module-scope `window`/`document`/`AudioContext`, and
 * crucially no gsap, which calls `gsap.registerPlugin(Flip)` at module scope
 * in src/components/board/useFlipReorder.ts and needs `window.matchMedia`.
 *
 * Those modules are reachable only through App.tsx → PedalBoard, which the
 * SSR entry deliberately does not import. The day someone adds a board import
 * to the guide tree, `npm run build` starts failing with a ReferenceError from
 * a Vite SSR bundle — an unpleasant thing to debug. This fails first, in the
 * test suite, and says why.
 *
 * jsdom is NOT loaded here. If this file ever needs a DOM shim to pass, the
 * invariant it protects has already been broken.
 */
describe('prerender safety', () => {
  it('has no DOM in this environment (guards the test itself)', () => {
    expect(typeof globalThis.window).toBe('undefined');
    expect(typeof globalThis.document).toBe('undefined');
  });

  it('renders every route to static markup with no browser globals', async () => {
    const { render, ROUTE_PATHS } = await import('@/prerender/entry-server');

    expect(ROUTE_PATHS).toHaveLength(17);

    for (const path of ROUTE_PATHS) {
      const page = render(path);
      expect(page.head, `${path} head`).toContain('<title>');
      expect(page.body.length, `${path} body`).toBeGreaterThan(500);
      expect(page.body, `${path} body`).toContain('<h1');
      expect(['main', 'guide']).toContain(page.shell);
    }
  });

  it('produces substantial prose on every guide page', async () => {
    const { render, ROUTE_PATHS } = await import('@/prerender/entry-server');

    for (const path of ROUTE_PATHS.filter((p: string) => p.startsWith('/guide'))) {
      const text = render(path).body.replace(/<[^>]+>/g, ' ');
      const words = text.split(/\s+/).filter(Boolean).length;
      // Thin pages rank worse than fewer strong ones, so this is a floor on
      // the content each URL is allowed to carry, not just a smoke test.
      expect(words, `${path} word count`).toBeGreaterThan(180);
    }
  });

  it('rejects an unregistered path instead of emitting an empty page', async () => {
    const { render } = await import('@/prerender/entry-server');
    expect(() => render('/guide/not-a-real-section')).toThrow(/No route registered/);
  });

  it('emits a sitemap listing every indexable URL', async () => {
    const { sitemapXml } = await import('@/prerender/entry-server');
    const xml = sitemapXml();
    expect((xml.match(/<loc>/g) ?? [])).toHaveLength(15);
    expect(xml).toContain('<loc>https://gp200studio.com/</loc>');
    expect(xml).toContain('<loc>https://gp200studio.com/guide/loop-station</loc>');
    // The 404 must never be advertised.
    expect(xml).not.toContain('/404');
  });
});
